# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e3565debd18fb1fdcce03416cd785ceb504ae6f99002911e13e5f19b60f89b310f97568fc88a3b049ecd9089270b44812358b5c63560817808fdd3dde0972ac

test:
  secret_key_base: e182d5c6e76092b56db182ea37c44e13a8224895dc61f8308e6dc9b515cc001e2f9a089008ecbfe25a65a44d20277ea8537a861d10f93e82dc9e54d14f864feb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
